### ISSUE TITLE
Consider resetting git history

### ISSUE THREAD

**Issue by ThatOneCalculator** [letrad/EverIron#1]
Simply going back one commit allows people to download `passwords.db`. I won't be opening the file, but please know that this is a possibility.

How to clean git history: https://www.shellhacks.com/git-remove-all-commits-clear-git-history-local-remote/

![image](https://github.com/letrad/EverIron/assets/44733677/4d57052a-adfb-446b-94b0-fd3d04413638)

**Comment by letrad** [comment]
@ThatOneCalculator it had nothing in it anyways lol.
